### ISSUE TITLE
Remove Realms

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#13]
Apologies if I missed it, but what is the best way to remove Realms from the ROS?  I've tried rm'ing the .realm, .lock, and .management items from /var/realm/sync-services/user_data.  It seems to kill them, but they still show up in my list when using the Realm Browser.

I'm using latest ROS on Ubuntu 16.04.

**Comment by mrackwitz** [comment]
These are tracked in the admin-Realm which is located at the virtual path `/__admin`. You can open this Realm for now with the browser by directly specifying the URL and then delete the entry for the path from the `RealmFile` table.

We should offer an easier way to achieve this, e.g. via the dashboard.

**Comment by cmelchior** [comment]
How should this work if clients are currently accessing the Realm? I assume one of two things?

1) Do not allow deleting Realms while a session is open to them (too restrictive?)
2) Delete the Realm which will cause a session error on clients (which one?)

**Comment by TotemChris** [comment]
I think a combination of both of those.  Maybe there should be an indication in the dashboard/browser to show # of active sessions to that realm, and when you try to delete it, if it is > 0, pop up an alert with a "There are 20 active sessions, are you really really sure?" (maybe that should pop up anyway, even when 0).

**Comment by TimOliver** [comment]
Being able to do this programmatically would be very useful.

In the sharing branch of Realm Tasks, each list of to-do items is backed by a separate synchronized Realm. If the user decides theyr'e done with that list and elect to delete it, the reference to the Realm is removed from the master list (so it disappears from the UI), but it still lingers on the server (and is visible in the Realm browser). This is somewhat unfortunate since it means the Realm is lingering on the server, but has now become inaccessible to the app itself.

It makes sense that once a Realm has finished being useful to the user, some sort of mechanism should be available to mark the Realm for deletion, allowing ROS to clean it up when it can.

**Comment by jpsim** [comment]
What makes this a bit tricky though is that if another client hasn't updated and still thinks that Realm exists, :boom:.

Or if a new client connects to the first time, they'll go through the whole history transaction by transaction, hitting points in time at which the data graph now has parts missing.

These situations can be partly mitigated by collapsing changesets.

But there's no way to fully address this without introducing new compromises, AFAICT.

**Comment by gritzko** [comment]
https://twitter.com/jaykreps/status/582580836425330688?lang=en

> Jay Kreps‏ @jaykreps
> The irony of distributed systems is that data loss is really easy but deleting data is surprisingly hard.

**Comment by gritzko** [comment]
From the dist-sys perspective, there are two solutions:

1. unlink (those still having a link can see the data. if none, the data gets garbage collected)
2. erase (the data is painted-over/tombstoned/vandalized/erased)

Their semantics is different, so it makes sense to have both. _Unlink_ should probably happen at the admin realm level. _Erase_ needs an OT implementation.

**Comment by gritzko** [comment]
The next release of ROS has trashcan buttons.
