### ISSUE TITLE
Sync a Realm between multiple devices of a user

### ISSUE THREAD

**Issue by kristofer** [realm/realm-mobile-platform#15]
So I'm thinking about using this as a means to sync a user's realmdb from one iOS device to another.

is that an easy idea to implement, or is this ROS idea really more for cross-user-base syncing?

I guess what I'm trying to ask - I can see where ROS would be quite handy for an "uber-like cab tracking" app, where all users get to see all cabs and RT updates are central to the app as a bunch of users all see the real time state of the data model.

what about for app where I'm looking to (merely) cross-devices sync a user's personal realmdb?

**Comment by mrackwitz** [comment]
The Realm Object Server is capable to handle both scenarios and basically any mixed forms of both. Beyond that the document-based permission system also allows to sync individual Realms between arbitrary subset of users and all their devices. Let me know if you have further questions.

**Comment by kristofer** [comment]
so I manage a lot of user objects in a icloud schema, but use realm as the "index" database to make the UI performant. 
I'm trying to find a way to not have to load each and all of the icloud objects (to recreate the index in realm) when I detect that the device used this time is different than the device used last time. 

would ROS be the only way I can do this? or is there something I don't understand about App Shared Groups that would be helpful?

**Comment by kristofer** [comment]
so yes: where is "document-based permission system" described?

**Comment by bigfish24** [comment]
Using ROS would be easier than iCloud since you could just represent the user data in a synchronized Realm and then whatever device the user is using, you simply allow the user to login and open the same synchronized Realm and ROS will keep everything in sync. The free version of ROS is specifically gear for this use-case of syncing a user's data across his/her devices.

The permission system does not yet have a public API, but will be coming out soon. You will be able to assign permissions to Realms such that multiple users can share access to a Realm, with either read and/or write permission.
