### ISSUE TITLE
Support for serverless architecture

### ISSUE THREAD

**Issue by keshavkaul** [realm/realm-mobile-platform#154]
## Goals

Is there any support for serverless architectures like AWS Lambda?

## Expected Results

Expected to see support for Serverless Architectures.

**Comment by bigfish24** [comment]
The Node SDK allows you to register "lambdas" or specifically get a callback in JS whenever synced Realms change. This is similar to AWS Lambda in terms of functionality, although much easier to manage because you don't have to worry about an API gateway, the same data in the Realm on the device is available in the callback reflecting the data on the device. Note this is available in the professional and enterprise editions.

**Comment by bigfish24** [comment]
More about our event handling is in our [docs](https://realm.io/docs/javascript/latest/#event-handling). There is a demo app [Scanner](https://realm.io/docs/tutorials/scanner/) that shows it off as well.
