### ISSUE TITLE
'realm::_impl::TransactLogParser::BadTransactLog' during startup

### ISSUE THREAD

**Issue by molind** [realm/realm-mobile-platform#197]
## Goals

Start realm object server

## Expected Results

Object server started

## Actual Results

Crash during start.

## Steps to Reproduce

It's crashed all the time now, since update to 
Get:2 https://packagecloud.io/realm/realm/ubuntu xenial/main amd64 realm-object-server-developer amd64 1.7.2-43 [51.0 MB]

## Code Sample

None.

## Version of Realm and Tooling

- Realm Object Server Version: 1.7.2
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu 16.04 inside Docker

## Logs

```
$ docker-compose up
Recreating realm_realm_1
Attaching to realm_realm_1
realm_1  | 2017-05-24T15:24:34.294Z - info: Logging to file /var/log/realm-object-server.log at level 'info'.
realm_1  | terminate called after throwing an instance of 'realm::_impl::TransactLogParser::BadTransactLog'
realm_1  |   what():  Bad transaction log
realm_1  | Aborted (core dumped)
realm_realm_1 exited with code 134
```

**Comment by Redth** [comment]
Was seeing this too.  I updated from 1.3.0 to 1.7.2 and after that update this happened.  I do have a copy of the data dir that I made before restoring from a backup, but I'd love to be able to possibly recover some of the realms that were lost during this process.  At this point when I made a backup, a number of realms could not be backed up, so they are currently lost.

**Comment by molind** [comment]
Using strace I found guilty file. realm-object-server crashed during migration of this file: 

[488cfbc9fa897b2609203effa07e27d9.zip](https://github.com/realm/realm-mobile-platform/files/1035485/488cfbc9fa897b2609203effa07e27d9.zip)

**Comment by Redth** [comment]
@molind can you explain how you found the offending file in a bit more detail? Thanks!

**Comment by molind** [comment]
@Redth I started realm-object-server, then checked all files it opened during migration by running `strace -e open -p <realm pid>`. And broken file is the one you see last before realm is crashed. You need to move all files of that realm out of the user_data folder.

**Comment by kspangsege** [comment]
@molind Can you share the code (classes) that define the schema, that you use with the uploaded file (`galileo.realm`)?

I was able to reproduce the crash that you see.

Prior to 1.7.2, the server only stored the history of changes, not the actual state of the Realm. Now it stores the Realm state too. When you upgrade to 1.7.2 (or later), we reconstruct the state from the history, and that is when the crash occurs. It happens due to a nonsensical instruction in one of the historical changesets (a `set_bool()` with a row index that is out of range).

Unfortunately, I cannot say much about how this happened, at least not yet. Also, to be honest, I don't think we will be able to resurrect the file.

On the other hand, due to the fact that we now have Realm states on the server, changesets coming in from clients are now validated much more strictly, and this means that if a bad instruction is produced in the future, we will likely detect it much earlier, and prevent that it is ever submitted to the servers history.

**Comment by kspangsege** [comment]
@molind As I alluded to above, we will unfortunately not be able to rescue that particular Realm file (`galileo.realm`), or others that have corrupt histories.

The corrupt history ultimately arose due bugs in the creation of, of transformation of changesets before they were added to the servers history. Such bugs may, or may not still exist, however, since the latest version of the server performs strong validation of incoming changesets, it is able to reject those that are invalid, allowing us to pinpoint the bug, and preventing those changesets from being added to the servers history.

It may be that you have other Realm files on the server that are not affected by this problem. If so, and if you are interested in rescuing those, you do that by deleting all the Realms that cause the migration process to crash (one by one), and thereby allowing for the migration process to complete.

Let me know if you need additional assistance with that.

cc @Redth
