### ISSUE TITLE
Is there any way to achieve time bound syncing

### ISSUE THREAD

**Issue by anujjpandey11** [realm/realm-mobile-platform#208]
##  Time Bound Syncing

I'm looking to build a one to many solution where one device will continuously push data to ROS, and other devices will sync it in time bound which will be between two dates or only last 30 days

.

##Is there any way we can build such system in which the device will sync only 30 days data without any manipulation in global data at ROS?
Something like below i can set which kind of time bound I want to applied on sync data

![screenshot_20170531-125730](https://cloud.githubusercontent.com/assets/18234556/26620660/512cd2ac-4601-11e7-8cbe-61526199df2b.png)

**Comment by kvap** [comment]
@anujjpandey11 Do you want to pull from ROS only the data which were modified after some point in time? Is that for reducing the network load or something else?

**Comment by anujjpandey11** [comment]
Yes I want to pull from ROS only the data which were modified/added after a point of time,yes it is for reducing the network call and I don't need data before that point but I want it on ROS.

**Comment by bigfish24** [comment]
To do this would require the professional edition so you can use the Node SDK to open a synced Realm. You could have a single Realm being written to by the client that pushes data to ROS. Then you could setup a chron script to query this Realm at continual intervals and then copy data from that Realm into other Realms synced to the other clients.

I will note this use-case though because it would be good to setup "chron'd" functions so you could just setup a Realm Function to this, similar to [AWS scheduled Lambda events](http://docs.aws.amazon.com/lambda/latest/dg/with-scheduled-events.html).

**Comment by anujjpandey11** [comment]
Thanks guys
