### ISSUE TITLE
Needs continuous backup to provide server redundancy

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-mobile-platform#21]
As suggested [here](http://stackoverflow.com/questions/40097563/server-replication-for-realm-mobile-platform/40105383#40105383), I'm filing a bug because to point out that there is no continuous backup feature yet available.

That's the best way I can see to provide server redundancy / high availability.

**Comment by teotwaki** [comment]
Hi @dsjstc,

Thanks for filing this. Please note that High Availability and Continuous Backup are significantly different features.

In order to clarify your request to the maximum, could you explain the use-case you have in mind? I have currently identified the following user scenarios:

- Manual backup (snapshot): this allows to implement scheduled (cron?) backups to secondary storage. This can be done on a live server. Manual intervention is required by an operator to bring the server back online---this could be scripted/automated, obviously.
- Continuous backup: this provides the ability to "stream" data to a hotswap slave. Some manual intervention will still be required to switch over---this could be scripted/automated, obviously.
- High Availability: multiple instances of the server running simultaneously on different hardware/availability zones, fronted by a load balancer of some sort, which ensures that clients can always access a live server.

The reason I am asking which one you are interested in, is because the way our protocol and the Realm Mobile Database are designed is inherently offline-first, and resilient to the fact that the server can be offline every once in a while. If you could detail your use-case/scenario as much as possible, it would be very helpful to us.

Thanks!

**Comment by dsjstc** [comment]
My use-case is a door-prize raffle with multiple mobile POS units.  It is critical to be able to ensure that the draw can take place at the end.  To that end, the certification requires that there be no single point of failure  -- if the server is incapable of conducting a draw after selling some tickets, the venue is in violation of the relevant law.

My use-case could be met with continuous backup or with HA.  It would be OK for there to be an interruption while the backup system is made live, however.

**Comment by cain004** [comment]
I think that HA would be the route to go. If someone is using the Event Framework to validate data based on a change, a highly available system would be required. For a large scale enterprise system, HA is always going to be required.

**Comment by dsjstc** [comment]
An alternative that just occurred to me:

Allow the client to modify the configuration of an existing realm to point to a secondary server.  If that server contained the authentication credentials, I'd assume that a re-sync from every client ought to completely rebuild the database.

As my goal is only to eliminate single-point failures, using the clients for redundancy would meet my need.  Continuous backup from primary to secondary wouldn't even be necessary for anything beyond the credential database.

**Comment by teotwaki** [comment]
Hi @dsjstc,

Thanks again for your input. The thing isn't actually that simple. For example, you would have to guarantee that the client doesn't have a more advanced history than the server. As it currently stands, the server would terminate the incoming connection because it is "unmergeable".

We have a team of 3 people currently brainstorming about this. I'll keep you posted as regards progress.

**Comment by teotwaki** [comment]
Continuous backup is now a feature of the Enterprise Edition.
