### ISSUE TITLE
ROS 2.0 Beta: Logs Page Shows No Content

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#257]
_Realm Object Server v2.0.0-rc2, Ubuntu 16.04.3, Chrome (Mac) Version 60.0.3112.101_

When I click on the **Logs** page, it doesn't show anything:

![image](https://user-images.githubusercontent.com/2513753/29690767-2b161460-88dd-11e7-92c1-cbecdd9ca045.png)
There are no script errors or asset 404s in the browser. I have tried a hard refresh in Chrome.

The debug logs from the server don't show any unusual activity, either:

![image](https://user-images.githubusercontent.com/2513753/29690791-487644ee-88dd-11e7-84a7-3687b65865b4.png)

I know that's not much help, but just wanted to log it in case someone else runs into this. 🙂

**Comment by kraenhansen** [comment]
Thanks for reporting this @cliftonlabrum. I've tried to reproduce the error by spinning up an Ubuntu 16.04 docker image running Realm Object Server v2.0.0-rc2 but I cannot reproduce this error.

I have a couple of followup questions that might help me narrow down the issue:
1. Can you confirm that this is the developer version of ROS that you're using?
2. From where / how did you install this version?
3. Have you accessed ROS on the same hostname and port before in a previous version? If this is the case - can I ask you to "force update" your browsers cache? (Apple + R or command + R on a Mac). I am suspecting that your browser might be caching a different version of the frontend which is not compatible with the updated backend and is therefore failing.

**Comment by cliftonlabrum** [comment]
Hi Kræn, thanks for following up. Answers below:

1. Yes, I'm using the developer edition. **2.0.0-rc2-285**
2. I was contacted by Avi Warner who told me about the beta, and then Adam Fish gave me the package URL to install it on Ubuntu. Perhaps that's because I'm part of the Realm MVP program. They were trying to help me avoid a migration later for an app I'm about to release.
3. No, I installed this version of the ROS on a fresh Digital Ocean droplet. I've done a hard refresh in Chrome many times. 

I just looked at the page source, and here's what the markup is rendering:
![image](https://user-images.githubusercontent.com/2513753/29783756-664c16e6-8bd6-11e7-9cd5-7caf8dcce799.png)

**Comment by cliftonlabrum** [comment]
Also, on that page, there are 3 HTTP requests made. Here are the calls and results:

**- 1 and 2 (same request twice) -**
> /api/info
`{"version":"2.0.0-rc2","flavor":"developer","setupRequired":false}`

**- 3 -**
>/api/logs/config
`{"levels":["all","info","warn","error"],"path":"/var/log/realm-object-server.log","bufferSize":1000}`

I will email you my log file in case the app is failing to parse it when it pulls it from the server.

**Comment by kraenhansen** [comment]
Thanks for looking into this and for the answers!

It looks like the issue is the Log React component not mounting correctly. I suspected that this had something to do with the connection from that not being able to establish because the dashboard is served over HTTPs - but I cannot reproduce that myself.

Is this something you need acute? If not - I want to thank you again for submitting the issue and ask for you to update to the next available version of ROS when it comes out. It will have a significantly different way of viewing the logs, why I doubt that the issue persists after that upgrade.

Please feel free to re-open this if you need a faster solution for the issue than the next available upgrade - or if the issue persists after the upgrade.
