### ISSUE TITLE
Has whole realm object in mobile device?

### ISSUE THREAD

**Issue by mobilestar0223** [realm/realm-mobile-platform#3]
Hello.
I'm very impressed on `**Realm Mobile Platform**` and this is amazing.
But I have one question about it.
Realm mobile platform synchronize local object to realm object server.
I think realm object is always stored in local and when mobile is online, this object is sync to server.
**So, mobile has same realm objects as amount of data that object server has, I think.**
Am I right or not.
**And can I use this mobile platform as mobile backend?**
Please explain about it.
Thanks.

**Comment by DiogoAndre** [comment]
Hi @mobilestar0223, 

> So, mobile has same realm objects as amount of data that object server has, I think. 

Currently, I believe yes. And based on a comment on a [StackOverflow question](http://stackoverflow.com/questions/39758576/realm-mobile-platform-can-realm-be-used-as-a-database) there seems to be a feature called _partial replication_ that will provide, well, partial replication.

**Comment by mobilestar0223** [comment]
Thanks, Diogo.

**Comment by teotwaki** [comment]
Hi mobilestar0223,

As Diogo indicated, yes, the server will use at least as much data as the client. In fact, the server has to keep a full history of all changes in order to allow new clients to get the Realm, so the server's storage requirements will always be at least the sum of all the clients' Realms.

As for your other question, whether you can use the Realm Mobile Platform as a "mobile backend", I'm not entirely sure what you mean, so my default answer would be "Of course" :D. Could you clarify that statement, so I can give a more accurate answer?

Thanks,

**Comment by mobilestar0223** [comment]
Thanks for your answering, teotwaki.
But I mean, can realm mobile platform be used as 'backend' like Parse or Firebase?
I understand server's storage store all client's Realms but I don't know clearly whether client have same data as server (also server has all client's realm) or not?
If you don't mind, please make me clearly about it.
Thanks.
