### ISSUE TITLE
Do you have a public Slack community?

### ISSUE THREAD

**Issue by TofPlay** [realm/realm-mobile-platform#43]
Hi,
Do you have a public Slack community for Realm Mobile Plaform?

**Comment by ianbradbury-bizzibody** [comment]
Although there is no specific channel for ROS - there is this Slack community.

realm-public.slack.com

I am not 100% clear if it is an officially sanctioned gathering.

**Comment by bmunkholm** [comment]
No we don't have that. The Slack channel mentioned is primarily used for
our Japanese community to experiment with that medium. While Slack might be
a fine medium for community communication we don't find it suitable for
support for a number of reasons.
If you have general questions as to how to do certain things StackOverflow
is the preferred medium, while Github is great for feature requests or bug
reports.

Does that cover your communication needs?

Cheers

**Comment by TofPlay** [comment]
@bmunkholm thanks for your answer. Personally I'm not a big fan of StackOverflow, to much noise. Most of the time I'm wasting my time trying to find a truly possible answer helpful. As you mention GitHub is good for feature requests or bug reports. And in fact, like you, I'm not a real fan of Slack. But from time to time it's helpful to be able talk live with someone.  If you prefer to use another tool instead of Slack it's okay for me. My be you can create your own tool with RMP 😉.  It might make a good demo 😉

**Comment by ianbradbury-bizzibody** [comment]
Like @TofPlay - I am also not a fan off SO. In fact I recently deleted a question I posted about ROS because I just could not be bothered to deal with the "go away newbie - don't ask such feeble questions here" comment from some UTOA user.  

What I find is missing from the Realm community is a place to go and just chat and discuss ideas and problems.  Stackoverflow is not the right place for that.  GitHub is not the place for that. There should be somewhere and if you're (Realm) not careful someone will create a place and you might loose the initiative.

**Comment by bmunkholm** [comment]
This is a super useful discussion to have and we love your input here! And
very interesting perspective of SO. We are discussing if a Realm specific
forum would be better to capture common issues and spur discussion and
cooperation in the community.

Thanks a lot for the feedback, and we appreciate more comments on this
topic.

**Comment by teotwaki** [comment]
@ianbradbury-bizzibody,

I think we (Realm) are fine if somebody else wants to foster that community---we're all about community building. We just have to be careful about spreading ourselves too thin. Support is quite often a massive drain on a company (especially a small one like ours), which is why we've in the past elected to use SO---even though it doesn't suit everyone, we've received a lot of help from the community in organising things, and administering it.

I'm an old-school IRC user, so although Slack is way too fancy with me, I've been using it happily for some time. This being said, I'm not convinced it's the perfect match for the discussions you're thinking of. Mainly, I feel like it would be complicated to organise all the different bindings properly in a public Slack. This might be my own bias, though (I remember that every language channel on Freenode had its own very specific rules, quite often conflicting with the next one).

I think it might be worth just trying it out for size, with a single channel, and seeing how it evolves. @bigfish24, @pkopacki, @dhmspector what do you think?

**Comment by ianbradbury-bizzibody** [comment]
@teotwaki - I can fully appreciate everything you say.  It's difficult.

I definitely agree with your point about Slack being the perfect match for better discussion.  So far I've only seen Slack work well for detailed discussion when the number of participants is low and make good use the channels feature.
