### ISSUE TITLE
Question about scaling and "server less"/offline first

### ISSUE THREAD

**Issue by nmccann** [realm/realm-mobile-platform#62]
Hi I was reading an example for the Enterprise edition's [Event Handling](https://realm.io/docs/realm-object-server/#event-handling) functionality, and just recently watched Alexander Stigsen's talk about an [Offline First world](https://realm.io/news/serverless-alexander-stigsen-in-an-offline-first-world/) - I was however wondering how the Realm Mobile Platform deals with scaling and the possible concurrency issues it may introduce.

In the Event Handlng example, changes to Coupons are being observed. When a change comes in, the Coupon is validated. But what if you had multiple instances observing these changes? Would they all get notified of a new Coupon at the same time and validate it multiple times? If that is the case, that could be dangerous for actions that should only happen once - for instance processing a payment.

Is it that developers are expected to have only one observer and then build a dispatching/load-balancing mechanism to redirect the changes? Or is there some way to "lock" the Coupon so no other observers will get it?

I guess I'm unsure if this is something that the Realm Mobile Platform is going to leave as an exercise for developers, or something that is going to be provided alongside the Enterprise solution.

Thank you for your time,
Noah

**Comment by bigfish24** [comment]
First thanks for asking this question and exploring the product deeply.

Right now we don't offer an automatic balancing system for events. However, the event handling enables the developer to split event handling up on their own. In the simplest scenario you can run the event handling on the same machine as the sync server. However, you can then break it up and run the event handling on another machine than the Realm Object Server because the event handling works as a client of the server. Furthermore, you can filter which Realms to observe, such that you can run event handling for part of the Realms being managed by the server on one machine and others on other machine(s). The result is you have the flexibility to architect the event handling to match the scale and complexity of your application. Further automating this is definitely an area we want to continue to explore as well.

**Comment by nmccann** [comment]
Thank you for the quick reply. So it sounds like that would lend itself well to micro services - as you scale you would try to have instances that just perform a single function (like payment processing) so they don't conflict with other instances.

However, I could see load balancing still being useful for reliability purposes and services that have tons of users. But that could be in addition to the micro service approach.

Something of an unrelated question/comment - but I've seen talk (in other issues) of pricing level between Developer and Enterprise. Instead of introducing a new pricing level, what about a different license scheme for learning? Event handling seems really cool, but it also seems like it requires a new kind of thinking and it would be great to play around and experiment with it - even if the result can't be used for commercial purposes. This would help devs to better understand the technology which helps when trying to convince an Enterprise company to take a chance on something new.

**Comment by teotwaki** [comment]
@nmccann Could you create a new issue/discussion for this, just so that we don't mix everything up? Thanks.

**Comment by teotwaki** [comment]
Closing this in favour of #77.
