### ISSUE TITLE
Pricing Model

### ISSUE THREAD

**Issue by nmccann** [realm/realm-mobile-platform#64]
I've seen talk (in other issues) of a possible pricing level between Developer and Enterprise. Instead of introducing a new pricing level, what about a different license scheme for learning? 

My reasoning is that Event Handling seems really cool, but it also seems like it requires a new kind of thinking and it would be great to play around and experiment with it - even if the result couldn't be used for commercial purposes. This would help devs to better understand the technology which helps when trying to convince an Enterprise company to take a chance on something new.

**Comment by bigfish24** [comment]
@nmccann we recently announced the Professional Edition which gives you access to the Node.js SDK: https://realm.io/news/introducing-realm-mobile-platform-professional-edition/

You can sign up for a 60 day trial and get access immediately: https://realm.io/pricing/realm-professional-edition/. The pricing starts at $1500/month since this is targeted at medium sized businesses.
