### ISSUE TITLE
Know when Realm loads all data at first setup

### ISSUE THREAD

**Issue by Jauzee** [realm/realm-mobile-platform#72]
How can I know that initial data was loaded?

Currently I configured Realm this way:
· Do we have any data in the Realm?
· If no, addNotificationBlock.
· If we receive first notification, stop the token and configure UI.

This way I face that only part of data was loaded.

Can I know this without some workarounds?

**Comment by teotwaki** [comment]
Hi @Jauzee,

We're working on a feature to help you manage this in the short future. Please stay tuned.

**Comment by Montrazul** [comment]
@Jauzee How do you check if the Realm Object is newly created?

**Comment by monajafi** [comment]
is there any progress about this feature. It's highly required for offline conflict resolution.

**Comment by bigfish24** [comment]
You can monitor download progress in 2.3: https://realm.io/news/realm-objc-swift-2.3/

**Comment by monajafi** [comment]
what about realm java?

**Comment by kneth** [comment]
It didn't make it into Realm Java 2.3.0. You can follow the progress in https://github.com/realm/realm-java/issues/4104. We hope to implement it soon (currently scheduled for Realm Java 2.5.0).

**Comment by monajafi** [comment]
Thanks a lot and good job

**Comment by monajafi** [comment]
I can't find sync progress and notification in realm java 3.0 already it was planned for version 2.5
when do you estimate this feature will be implemented for java?

**Comment by kneth** [comment]
@monajafi Sorry, it wasn't ready for 3.0 (to be more accurate, it's blocked by https://github.com/realm/realm-java/issues/3742).

**Comment by monajafi** [comment]
Thanks for your efforts I highly need that for offline conflict resolution.

**Comment by Montrazul** [comment]
Are there any news to this? I would like to be able to download the very last state of an existing realm database. Right now when I install the App and login with an already existing user the downloading of the realm takes quite much time since its processing every operation which was ever performed on the realm database. 

It would be much better if I could just download the very last state as it currently is.

**Comment by bigfish24** [comment]
We haven't yet added support to do this but we have made internal changes in the server to get us there. The server initially only held the full logs of all the operations, but recently we added the ability to store the state. This was primarily done so that we can do things in the server like validate incoming changes against the state, but it does mean we have the final state to use for other purposes. The next piece of functionality to use it will be an updated continuous backup system, which operates in the manner you describe: when a backup connects for the first time, the main server sends the final states to speed up getting the backup in place, then switches to sending the operations. It is our plan to enable the same functionality for mobile clients, likely Q3 timeframe though.

**Comment by brayanL** [comment]
When this solution will be, it is very important., thank you for great work with Realm....

**Comment by bigfish24** [comment]
@brayanL to clarify we now have an `asyncOpen` method that allows you to asynchronously open the Realm in which the callback is fired once the Realm is fully downloaded: https://realm.io/docs/swift/latest/#asynchronously-opening-realms

What I was referring to above was an optimization where this download would be faster, but the general capability to know when a Realm is downloaded is available now.

**Comment by brayanL** [comment]
Great answer @bigfish24 I achieved to Know when Realm loads all data at first time, with **_asyncOpen_** with **rxjava** is all awesome, i show a progress bar in Splash Screen until that the callback return onSucces. Thank you so much...!
