### ISSUE TITLE
Can't run RealmTasks demo app using Xcode 8.2

### ISSUE THREAD

**Issue by felipeplets** [realm/realm-mobile-platform#91]
Once I open the project in Xcode 8.2 it asks to migrate the project, after migration it shows the error: 

> Module compiled with Swift 2.3 cannot be imported in Swift 3.0.2: /realm-mobile-platform/demo/RealmTasks/RealmTasks Apple/../../../SDKs/realm-cocoa_2.1.0/ios/swift-2.3/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64.swiftmodule

I understand that to work using Xcode 8.2 is necessary to update the demo app to use Ream 2.1.2.

**Comment by istx25** [comment]
Hey there, @felipeplets! Thank you for reaching out for support.

As far as I know, RealmTasks hasn't been fully updated to Xcode 8.2 by Realm and since you've gone through the migration yourself, please make sure you've also bumped the RealmSwift version in the `Podfile` as well.

Please change `pod 'RealmSwift', '~> 2.1.1'` to `pod 'RealmSwift', '~> 2.1.2'` on [line six](https://github.com/realm/RealmTasks/blob/master/RealmTasks%20Apple/Podfile#L6). From there, delete the `Pods/` directory and run `pod install` again and you _should_ be good to go.

Let me know how you get on. :-)

**Comment by jpsim** [comment]
That's not quite right. RealmTasks does in fact support Xcode 8.2, but requires Swift 2.3.

**Comment by TimOliver** [comment]
Yeah, we're assuming that Xcode 8.2 will be the last supported release of Swift 2.3 so we're prioritizing updating Realm Tasks for Swift 3 now. I'm working on that [in this branch](https://github.com/realm/RealmTasks/tree/to-swift-3) if you want to try it out.

But for the current master version, I would advise against running a migration and just continue using it in the  Swift 2.3 mode for now. :)

**Comment by felipeplets** [comment]
Thank you for the answers. 

@jpsim you are right, it works with Swift 2.3, my mistake, I just opened I went through the migration process. 

@TimOliver and @istx25 thank you for letting me know, I will the [RealmTasks](https://github.com/realm/RealmTasks) repo and try the swift-3 branch, maybe I can contribute to the migration.

**Comment by jpsim** [comment]
Glad to hear it.
