### ISSUE TITLE
Add Realm as a Pod dependency and release Podfile in the demo app

### ISSUE THREAD

**Issue by felipeplets** [realm/realm-mobile-platform#92]
I see it can make a lot easier to play with the demo enabling the users to install other dependencies or update the current ones (Cartography and Realm itself) if Podfile is released along with the RealmTasks demo App inside realm-mobile-platform.zip.

Is there any special reason to not release the Podfile along with the demo app?

**Comment by felipeplets** [comment]
@istx25 Just to make it clear, in this issue I was talking about the package: https://static.realm.io/downloads/mobile-platform/latest/realm-mobile-platform.zip

**Comment by jpsim** [comment]
> Is there any special reason to not release the Podfile along with the demo app?

Yes, in a nutshell, the idea of shipping prebuilt binary packages and examples is to use those binaries from the zip in the Xcode project, so build times are much faster (since you're not building Realm or any other dependencies) and building doesn't require an Internet connection.

If you want to build with CocoaPods, I suggest you build from the source repo here: https://github.com/realm/RealmTasks

**Comment by istx25** [comment]
@jpsim's response seems sufficient. Closing but feel free to reopen if there's any follow-up questions.
