### ISSUE TITLE
Mark properties unsyncable in a Realm object

### ISSUE THREAD

**Issue by chrisamanse** [realm/realm-mobile-platform#97]
Is there such a way that we can mark properties in a Realm object as unsyncable, i.e. doesn't upload data to the Realm Object Server?

Ex.

```swift
class FileObject: Object {
    var fileID: String
    var temporaryPath: String
    var blobs: [FileBlob]
}
```

The expected outcome is that the property `temporaryPath` property of `FileBlob` will not be uploaded and its value is only stored locally. This has different behavior from `ignoredProperties` as this will not save the property to the Realm file.

**Comment by bigfish24** [comment]
@chrisamanse right now this is not possible. A synchronized Realm transfers all the data added to it.  Instead, you could separate out the data that shouldn't be synced into a standalone Realm. You can link the non-synced data via a shared key with the synced data.

In general, you should treat Realms as lightweight data containers. Instead of being able to selectively synchronize data in a Realm, you can split it up into multiple Realms and then selectively synchronize what you need. While we want to improve this over time, if you think of it in this fashion you can still power most data models with it.

**Comment by bmunkholm** [comment]
I'll close this for now, @chrisamanse if Adams suggestion doesn't solve the problem for now, feel free to reopen.
